name: 'Setup Zarf'
description: 'GitHub Action for Installing Zarf'
inputs:
  version:
    description: 'The Version of Zarf to Install'
    required: false
    default: '0.22.1'
  download_init_package:
    description: 'Download Zarf Init Package'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'