name: 'Continuous Integration'

on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Package Dependencies
      run: npm ci

    - name: Test
      run: npm test
      shell: bash

    - name: Scan current project
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: "."
        fail-build: true
        severity-cutoff: critical
    
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}

    - name: Upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Create SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

    - name: Scan SBOM
      uses: anchore/scan-action@v3
      with:
        sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
        fail-build: true
        severity-cutoff: critical
