name: 'Continuous Integration'

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - main

jobs:
  test:
    name: Cross-platform Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install Package Dependencies
      run: npm ci

    - name: Test
      run: npm test
      shell: bash

    - name: Scan current project directory
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: "."
        fail-build: true
        severity-cutoff: critical
    
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}

    - name: Upload Anchore scan SARIF report for viewing 
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Upload Grype scan results as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: Grype Report
        path: ${{ steps.scan.outputs }}

    - name: Set commit short sha var as output
      id: short-sha-var
      run: GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)

    - name: Create SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: "${{ github.event.repository.name }}-${{ steps.short-sha-var.env.GITHUB_SHA_SHORT }}-sbom.spdx.json"

    - name: Scan SBOM
      uses: anchore/scan-action@v3
      with:
        sbom: "${{ github.event.repository.name }}-${{ steps.short-sha-var.env.GITHUB_SHA_SHORT }}-sbom.spdx.json"
        fail-build: true
        severity-cutoff: critical
